runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /static/js/(.*)
    static_files: static/js/\1
    upload: static/js/(.*)
  - url: /static/css/(.*)
    static_files: static/css/\1
    upload: static/css/(.*)
  - url: /static/media/(.*)
    static_files: static/media/\1
    upload: static/media/(.*)
  - url: /(.*\.(json|ico|png|txt|md|jpg|xml|svg|webp))$
    static_files: \1
    upload: .*\.(json|ico|png|txt|md|jpg|xml|svg|webp)$
  # Public
  - url: /
    static_files: index.html
    upload: index.html
  - url: /.*
    static_files: index.html
    upload: index.html
  # Public
  # - url: /
  #   static_files: index.html
  #   upload: index.html
  # - url: /.*
  #   static_files: index.html
  #   upload: index.html
