import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faPlay,
  faCube,
  faShoppingBasket,
  faHeartbeat,
  faBookOpen,
  faUser,
  faClock,
  faCoins,
  faHeadset,
  faLink,
  faListUl,
  faShieldAlt,
  faFlagCheckered,
  faFrown,
} from "@fortawesome/free-solid-svg-icons";
import {
  faTwitter,
  faDiscord,
  faInstagram,
  faFacebook,
  faGithub,
  faGitlab,
  faReddit,
  faSkype,
  faYoutube,
  faSteam,
  faTwitch,
} from "@fortawesome/free-brands-svg-icons";
library.add(
  faPlay,
  faClock,
  faCube,
  faShoppingBasket,
  faHeartbeat,
  faBookOpen,
  faUser,
  faCoins,
  faHeadset,
  faLink,
  faListUl,
  faShieldAlt,
  faFlagCheckered,
  faFrown,
  faTwitter,
  faDiscord,
  faInstagram,
  faFacebook,
  faGithub,
  faGitlab,
  faReddit,
  faSkype,
  faYoutube,
  faSteam,
  faTwitch
);
